# Generated by Django 5.1.1 on 2024-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordQuiz',
            fields=[
                ('id', models.AutoField(help_text='поле индекса нужно для сохранения прогресса', primary_key=True, serialize=False)),
                ('word', models.CharField(help_text='слово изучаемого языка', max_length=50, unique=True)),
                ('translation', models.CharField(help_text='перевод слова', max_length=50)),
            ],
        ),
    ]
